name: abcd
channels:
  - defaults
dependencies:
  - python=3.8
  - scikit-learn
  - pandas
  - tqdm
  - cudatoolkit=10.2
  - pytorch
  - torchaudio
  - torchvision
  - tensorflow
  - seaborn
  - pip:
      - dill
      - fonttools
      - keras
      - libclang
      - matplotlib
      - multiprocess
      - psutil
      - scikit-multiflow
      - sortedcontainers
      - tensorboard
      - tensorboard-data-server
      - tensorflow
      - tensorflow-io-gcs-filesystem
      - tf-estimator-nightly